services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - PG_URL=${PG_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./internal/adapters/repo/migrations/0001_init.sql:/docker-entrypoint-initdb.d/0001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
  app:
    container_name: pr-service
    build: .
    environment:
      - HTTP_URL=${HTTP_URL}
      - HTTP_PORT=${HTTP_PORT}
      - PG_URL=${PG_URL}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      db:
        condition: service_healthy
